### ISSUE TITLE
Wrong PluginProperty.to_java method generated

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-plugin-framework-ruby#48]
See https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/gen/plugin-api/plugin_property.rb#L41.

**Comment by sbrossie** [comment]
Should be fixed with commit 25fce3ae8b4d155208830ee9a84e9c89d374a954. Released  4.4.0 to fix the issue.
