### ISSUE TITLE
Don't assume store method exists

### ISSUE THREAD

**Issue by lstephen** [killbill/killbill-plugin-framework-ruby#49]
The `store` method of a gateway is called here: https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/helpers/active_merchant/payment_plugin.rb#L171

Some gateways do not implement this method as they do not support it. As mentioned in the Active Merchant documentation it is optional: http://www.rubydoc.info/github/activemerchant/active_merchant/ActiveMerchant/Billing/Gateway

A workaround is to have a gateway implement a dummy store method, but perhaps there can be a check added to see if a gateway supports it or not.

**Comment by pierre** [comment]
None of the ActiveMerchant gateways will work out-of-the box after the code (and test code) has been generated, there will always be some modifications needed (even for the simplest gateways, such as [Stripe](https://github.com/killbill/killbill-stripe-plugin/blob/master/lib/stripe/api.rb#L30)).

If `store` isn't provided by the provider, just pass `options[:skip_gw] = true` by default in the `add_payment_method` implementation. The `killbill` gem will make sure the relevant state is persisted in the plugin tables, but [no remote call](https://github.com/killbill/killbill-plugin-framework-ruby/blob/master/lib/killbill/helpers/active_merchant/gateway.rb#L67) will be attempted.

**Comment by pierre** [comment]
Take a look at the [Litle](https://github.com/killbill/killbill-litle-plugin/blob/master/lib/litle/api.rb#L113) plugin for an example.

**Comment by lstephen** [comment]
> If store isn't provided by the provider, just pass options[:skip_gw] = true by default in the add_payment_method implementation.

Thanks, this is what I needed. :thumbsup:
